### ISSUE TITLE
Ability to specify an already existing Secret for SveltosCluster

### ISSUE THREAD

**Issue by prometherion** [projectsveltos/libsveltos#218]
When operating Clusters non-backed by Cluster API, Sveltos requires a `SveltosCluster` to be created: this is required to instruct Sveltos in pointing to which kubeconfig must be used to connect to the cluster.

The current implementation requires a Secret must already exist, with the current naming convention: `${SVELTOSCLUSTER_NAME}-sveltos-kubeconfig`. In some circumstances, such as Kamaji, the kubeconfig is already available, and that would require a duplication of Kubernetes resources, making even more complicated the rotation of its content in automated way.

My suggestion is to add a new field to the SveltosCluster API, something as:
```
apiVersion: lib.projectsveltos.io/v1alpha1
kind: SveltosCluster
metadata:
  name: dev1
spec:
  kubeconfigName: dev1-admin-kubeconfig
```

In case of an empty value, the backward compatible behaviour can be kept, as pointing to `${SVELTOSCLUSTER_NAME}-sveltos-kubeconfig`, otherwise, the user can specify an already existing secret.

I can take care of this implementation.
