### ISSUE TITLE
Default log-level is set to DEBUG

### ISSUE THREAD

**Issue by sim500** [projectsveltos/libsveltos#435]
## Expected Behavior
The sveltos components have a **log level set to INFO** by default

## Current Behavior
Installing sveltos via Helm, without changing or specifying any additional value, **the default log level** of all the sveltos components is set to **DEBUG**.
This issue causes the generation of more than **one milion log lines per hour** in the entire projectsveltos namespace.
The component that logs the most is apparently the **AddonManager**.

## Possible Solution
The Helm installation of sveltos, by default, without editing any value, should deploy a **DebuggingConfiguration** like the following:
``` yaml
apiVersion: lib.projectsveltos.io/v1beta1
kind: DebuggingConfiguration
metadata:
 name: default
spec:
 configuration:
   - component: AddonManager
     logLevel: LogLevelInfo
```

So it ensures that the AddonManager starts with the log-level set to INFO.

> It may be necessary to extend the configuration that sets `logLevel: LogLevelInfo` to all the other components as well.

## Your Environment
k8s version: **1.30-RKE2**
sveltos version: **0.46.1**, installed with Helm
